#!/bin/busybox sh
# RAM-only: no filesystem from eMMC is mounted.
set -eu
bb=/bin/busybox
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
exec /sbin/init
