[defaults]
    base_features = sparse_super,large_file,filetype,resize_inode,dir_index,ext_attr
    blocksize = 4096
    inode_size = 256
    inode_ratio = 16384
[fs_types]
    ext4 = {
        features = has_journal,extent,uninit_bg
    }
